[package]
name = "ext-danmuku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniz_oxide = "0.5.1"
tracing-subscriber = "0.3"
tracing = "0.1"
regex = { version = "1.1.8", features = ["pattern"] }